.TH ext2_cat
.SH NAME
ext2_access \- Prints file content to stdout
.SH DESCRIPTION
A basic program that retrieves the content of a file from an ext2 image
and prints it to stdout. This program can fully retrieve large files that
do not entirely fit into a direct block. 

.SH DESIGN DECISIONS
To allow for the driver to retrieve files too large
to fit in all the direct blocks, the driver reads the first level of 
indirect blocks, until actual file size is reached or all 255 indirect blocks
have been read. We only decided to check through one set of the indirect
blocks because all the files fit into both the direct and first set of indirect
blocks.

.SH AUTHOR
Irsal Jasebel Alsanea, Patrick Hayes, Felix Hu