.TH ext2_access
.SH NAME
ext2_access \- Implementation of a read-only driver for ext2
.SH DESCRIPTION
ext2_access is a read-only driver for ext2 that includes multiple basic and
higher level accessors.

.SH DESIGN DECISIONS
We tried to use as many definitions from ext2fs.h as possible to reduce
complexity.

.SH AUTHOR
Irsal Jasebel Alsanea, Patrick Hayes, Felix Hu